"use client";
/* eslint-disable @next/next/no-img-element -- la foto puede usar una URL configurada por el gimnasio */

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarClock, Edit3, Pause, Play, Plus, Search, Users, X } from "lucide-react";
import { actualizarEntrenador, asignarSociosEntrenador, cambiarEstadoEntrenador, crearEntrenador, getEntrenadoresAdmin } from "@/app/actions/entrenadores";

type Schedule = { dia: number; activo: boolean; desde: string; hasta: string };
type Branch = { id: number; nombre: string };
type Member = { id: number; nombre: string; apellido: string; documento: string; entrenadorId: number | null };
type Trainer = { id: number; bio?: string | null; foto?: string | null; especialidades: string[]; horarios?: Schedule[] | null; estado: string; user: { name: string; email: string; username?: string | null; tenantMemberships: Array<{ estado: string }> }; sucursales: Branch[]; socios: Member[]; _count: { rutinas: number; clases: number; mediciones: number } };
type Data = { trainers: Trainer[]; branches: Branch[]; members: Member[] };

const days = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];
const defaultSchedule = (): Schedule[] => days.map((_, dia) => ({ dia, activo: dia > 0 && dia < 6, desde: "08:00", hasta: "16:00" }));

export default function TrainersPage() {
  const [data, setData] = useState<Data>({ trainers: [], branches: [], members: [] });
  const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Trainer | null>(null); const [assigning, setAssigning] = useState<Trainer | null>(null);
  const [modal, setModal] = useState<"profile" | "members" | null>(null); const [selectedMembers, setSelectedMembers] = useState<number[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { const result = await getEntrenadoresAdmin(); if (result.success) setData(result.data as unknown as Data); else setMessage(result.error || "No se pudo cargar"); };
  useEffect(() => {
    // La acción remota actualiza el estado sólo después de resolver.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, []);
  const filtered = useMemo(() => data.trainers.filter((trainer) => `${trainer.user.name} ${trainer.user.email} ${trainer.especialidades.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [data.trainers, query]);
  const run = async (action: () => Promise<{ success: boolean; error?: string }>, success: string) => { setBusy(true); const result = await action(); setMessage(result.success ? success : result.error || "No se pudo completar"); if (result.success) { setModal(null); await load(); } setBusy(false); };

  const submitProfile = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget);
    const schedule = days.map((_, dia) => ({ dia, activo: form.get(`activo-${dia}`) === "on", desde: String(form.get(`desde-${dia}`) || "08:00"), hasta: String(form.get(`hasta-${dia}`) || "16:00") }));
    const payload = { name: String(form.get("name") || ""), bio: String(form.get("bio") || ""), foto: String(form.get("foto") || ""), especialidades: String(form.get("especialidades") || "").split(",").map((item) => item.trim()).filter(Boolean), sucursalIds: form.getAll("sucursales").map(Number), horarios: schedule };
    const result = editing ? await actualizarEntrenador(editing.id, payload) : await crearEntrenador({ ...payload, email: String(form.get("email") || ""), username: String(form.get("username") || "") });
    if (result.success) {
      const password = "temporaryPassword" in result ? result.temporaryPassword : undefined;
      setMessage(password ? `Entrenador creado. Clave temporal: ${password} (guardala ahora, se muestra una sola vez).` : "Perfil actualizado"); setModal(null); await load();
    } else setMessage(result.error || "No se pudo guardar"); setBusy(false);
  };

  const openProfile = (trainer: Trainer | null) => { setEditing(trainer); setModal("profile"); };
  const openMembers = (trainer: Trainer) => { setAssigning(trainer); setSelectedMembers(trainer.socios.map(({ id }) => id)); setModal("members"); };
  const totalAssigned = data.members.filter((member) => member.entrenadorId).length;

  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-700">Equipo técnico</p><h1 className="text-2xl font-black">Entrenadores</h1><p className="text-sm text-slate-500">Perfiles, horarios, sedes y cartera de socios.</p></div><button onClick={() => openProfile(null)} className="flex h-11 items-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Nuevo entrenador</button></div>
    {message && <button onClick={() => setMessage(null)} className="w-full rounded-xl border border-cyan-200 bg-cyan-50 p-3 text-left text-sm font-bold text-cyan-900">{message}</button>}
    <div className="grid gap-3 sm:grid-cols-3"><Stat value={data.trainers.filter((item) => item.estado === "activo").length} label="Entrenadores activos"/><Stat value={totalAssigned} label="Socios asignados"/><Stat value={data.members.length - totalAssigned} label="Socios sin entrenador"/></div>
    <label className="flex max-w-md items-center gap-2 rounded-xl border bg-white px-3"><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar entrenador" className="h-11 flex-1 outline-none"/></label>
    <div className="grid gap-4 lg:grid-cols-2">{filtered.map((trainer) => <article key={trainer.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${trainer.estado !== "activo" ? "opacity-65" : ""}`}><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-cyan-100 text-xl font-black text-cyan-800">{trainer.foto ? <img src={trainer.foto} alt="" className="h-full w-full object-cover"/> : trainer.user.name.charAt(0)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{trainer.user.name}</h2><Status active={trainer.estado === "activo"}/></div><p className="truncate text-xs text-slate-500">{trainer.user.email} · @{trainer.user.username}</p><p className="mt-1 text-xs text-slate-500">{trainer.sucursales.map(({ nombre }) => nombre).join(" · ")}</p></div></div><div className="mt-4 flex flex-wrap gap-1.5">{trainer.especialidades.map((item) => <span key={item} className="rounded-lg bg-cyan-50 px-2 py-1 text-[11px] font-bold text-cyan-800">{item}</span>)}</div>{trainer.bio && <p className="mt-3 line-clamp-2 text-sm text-slate-600">{trainer.bio}</p>}<div className="mt-4 grid grid-cols-3 divide-x rounded-xl bg-slate-50 p-3 text-center"><Mini value={trainer.socios.length} label="Socios"/><Mini value={trainer._count.clases} label="Clases"/><Mini value={trainer._count.mediciones} label="Mediciones"/></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => openProfile(trainer)} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50"><Edit3 className="h-4 w-4"/>Editar perfil</button><button onClick={() => openMembers(trainer)} disabled={trainer.estado !== "activo"} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-40"><Users className="h-4 w-4"/>Asignar socios</button><button disabled={busy} onClick={() => void run(() => cambiarEstadoEntrenador(trainer.id, trainer.estado !== "activo"), trainer.estado === "activo" ? "Entrenador pausado" : "Entrenador reactivado")} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-40">{trainer.estado === "activo" ? <Pause className="h-4 w-4"/> : <Play className="h-4 w-4"/>}{trainer.estado === "activo" ? "Pausar" : "Reactivar"}</button></div></article>)}</div>
    {!filtered.length && <div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">No hay entrenadores para mostrar.</div>}

    {modal === "profile" && <Modal title={editing ? "Editar entrenador" : "Nuevo entrenador"} onClose={() => setModal(null)}><form onSubmit={submitProfile} className="grid gap-4 sm:grid-cols-2"><Field name="name" label="Nombre completo" required defaultValue={editing?.user.name}/>{!editing && <><Field name="email" label="Email de acceso" type="email" required/><Field name="username" label="Usuario" required/></>}<Field name="foto" label="URL de foto" type="url" defaultValue={editing?.foto} className="sm:col-span-2"/><Field name="especialidades" label="Especialidades separadas por coma" required defaultValue={editing?.especialidades.join(", ")} className="sm:col-span-2"/><label className="text-xs font-bold text-slate-600 sm:col-span-2">Biografía<textarea name="bio" defaultValue={editing?.bio || ""} rows={3} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><fieldset className="sm:col-span-2"><legend className="text-xs font-bold text-slate-600">Sucursales</legend><div className="mt-2 flex flex-wrap gap-2">{data.branches.map((branch) => <label key={branch.id} className="rounded-xl border bg-slate-50 px-3 py-2 text-sm font-bold"><input name="sucursales" type="checkbox" value={branch.id} defaultChecked={editing?.sucursales.some(({ id }) => id === branch.id) ?? data.branches.length === 1} className="mr-2"/>{branch.nombre}</label>)}</div></fieldset><ScheduleEditor value={editing?.horarios}/><button disabled={busy} className="h-11 rounded-xl bg-slate-950 text-sm font-bold text-white sm:col-span-2 disabled:opacity-50">{busy ? "Guardando…" : "Guardar entrenador"}</button></form></Modal>}
    {modal === "members" && assigning && <Modal title={`Socios de ${assigning.user.name}`} onClose={() => setModal(null)}><p className="mb-4 text-sm text-slate-500">Esta lista reemplaza la cartera completa del entrenador. Los socios marcados dejarán de estar asignados a otro entrenador.</p><div className="max-h-[55vh] space-y-2 overflow-y-auto">{data.members.map((member) => <label key={member.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><input type="checkbox" checked={selectedMembers.includes(member.id)} onChange={(event) => setSelectedMembers((current) => event.target.checked ? [...current, member.id] : current.filter((id) => id !== member.id))}/><span className="flex-1 text-sm font-bold">{member.apellido}, {member.nombre}</span><span className="text-xs text-slate-500">DNI {member.documento}{member.entrenadorId && member.entrenadorId !== assigning.id ? " · asignado a otro" : ""}</span></label>)}</div><button disabled={busy} onClick={() => void run(() => asignarSociosEntrenador(assigning.id, selectedMembers), `${selectedMembers.length} socios asignados`)} className="mt-5 h-11 w-full rounded-xl bg-cyan-700 text-sm font-bold text-white disabled:opacity-50">Guardar cartera</button></Modal>}
  </div>;
}

function ScheduleEditor({ value }: { value?: Schedule[] | null }) { const schedule = Array.isArray(value) && value.length === 7 ? value : defaultSchedule(); return <fieldset className="sm:col-span-2"><legend className="flex items-center gap-2 text-xs font-bold text-slate-600"><CalendarClock className="h-4 w-4"/>Horario semanal</legend><div className="mt-2 space-y-2">{days.map((label, dia) => { const item = schedule.find((row) => row.dia === dia) || defaultSchedule()[dia]; return <div key={label} className="grid grid-cols-[1fr_auto_auto] items-center gap-2 rounded-xl bg-slate-50 p-2"><label className="text-sm font-bold"><input name={`activo-${dia}`} type="checkbox" defaultChecked={item.activo} className="mr-2"/>{label}</label><input name={`desde-${dia}`} type="time" defaultValue={item.desde} className="h-9 rounded-lg border bg-white px-2 text-sm"/><input name={`hasta-${dia}`} type="time" defaultValue={item.hasta} className="h-9 rounded-lg border bg-white px-2 text-sm"/></div>; })}</div></fieldset>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><div className="max-h-[92dvh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div>{children}</div></div>; }
function Field({ name, label, required, type = "text", defaultValue, className = "" }: { name: string; label: string; required?: boolean; type?: string; defaultValue?: string | null; className?: string }) { return <label className={`text-xs font-bold text-slate-600 ${className}`}>{label}<input name={name} type={type} required={required} defaultValue={defaultValue || ""} className="mt-1 h-11 w-full rounded-xl border px-3 text-sm"/></label>; }
function Stat({ value, label }: { value: number; label: string }) { return <div className="rounded-2xl border bg-white p-4"><p className="text-2xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div>; }
function Mini({ value, label }: { value: number; label: string }) { return <div><p className="font-black">{value}</p><p className="text-[10px] uppercase text-slate-500">{label}</p></div>; }
function Status({ active }: { active: boolean }) { return <span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{active ? "Activo" : "Pausado"}</span>; }
